Repository SurPathHub/Dayong, pull requests merged in 2021-10, with the labels that each got.

#11 docs: python version, license and commit activity badges added
  README.md
Labels: hacktoberfest-accepted

#13 Add License to README.md
  README.md
Labels: hacktoberfest-accepted

#16 Fixes Issue #14: Add Github Action to check with flake8
  .github/workflows/lint.yml
Labels: hacktoberfest-accepted

#17 Prep for deployment and production
  .env.example
  Procfile
  README.md
  app.json
  dayong/bot.py
  dayong/components/event_component.py
  dayong/components/privilege_component.py
  dayong/components/slash_component.py
  dayong/configs.py
  dayong/impls.py
  dayong/interfaces.py
  dayong/tasks/celery.py
  dayong/tasks/medium.py
  dayong/tasks/news.py
  dayong/utils.py
  docs/README.md
  docs/commands.md
  docs/installation.md
  docs/setup.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#19 docs: Updated commands.md and created events.md
  docs/README.md
  docs/commands.md
  docs/events.md
Labels: documentation, hacktoberfest-accepted
